/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#333539",
        "surface-container-lowest": "#0c0e12",
        "on-primary-fixed-variant": "#004e60",
        "tertiary": "#ffd59c",
        "on-tertiary-fixed": "#291800",
        "outline": "#859399",
        "on-error": "#690005",
        "on-primary-fixed": "#001f28",
        "error-container": "#93000a",
        "surface-dim": "#111318",
        "outline-variant": "#3c494e",
        "on-surface-variant": "#bbc9cf",
        "on-primary": "#003543",
        "tertiary-fixed": "#ffddb1",
        "surface-tint": "#4cd6ff",
        "on-tertiary-fixed-variant": "#624000",
        "on-secondary-fixed-variant": "#5700c9",
        "primary-container": "#00d1ff",
        "primary-fixed-dim": "#4cd6ff",
        "primary": "#a4e6ff",
        "on-secondary-container": "#ddcdff",
        "tertiary-fixed-dim": "#ffba49",
        "secondary-container": "#7000ff",
        "surface-container-high": "#282a2e",
        "on-surface": "#e2e2e8",
        "error": "#ffb4ab",
        "surface-container-low": "#1a1c20",
        "on-secondary": "#3c0090",
        "on-tertiary-container": "#6b4700",
        "background": "#111318",
        "secondary": "#d1bcff",
        "on-secondary-fixed": "#23005b",
        "inverse-surface": "#e2e2e8",
        "on-tertiary": "#442b00",
        "surface": "#111318",
        "primary-fixed": "#b7eaff",
        "inverse-primary": "#00677f",
        "on-primary-container": "#00566a",
        "inverse-on-surface": "#2f3035",
        "on-background": "#e2e2e8",
        "tertiary-container": "#feb127",
        "secondary-fixed-dim": "#d1bcff",
        "surface-container-highest": "#333539",
        "secondary-fixed": "#e9ddff",
        "surface-container": "#1e2024",
        "surface-bright": "#37393e",
        "on-error-container": "#ffdad6",
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
